/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClassSchema extends BaseModel {
  static $columns = ['createdAt', 'homeroomTeacher', 'id', 'name', 'schedule', 'status', 'students', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare homeroomTeacher: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare schedule: string
  @column()
  declare status: string
  @column()
  declare students: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplianceSchema extends BaseModel {
  static $columns = ['completion', 'createdAt', 'dueDate', 'employeeName', 'id', 'moduleName', 'status', 'updatedAt'] as const
  $columns = ComplianceSchema.$columns
  @column()
  declare completion: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dueDate: string
  @column()
  declare employeeName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare moduleName: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CourseSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'learners', 'owner', 'progress', 'status', 'title', 'updatedAt'] as const
  $columns = CourseSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare learners: number
  @column()
  declare owner: string
  @column()
  declare progress: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GuardianSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'guardianName', 'id', 'phone', 'relation', 'status', 'studentName', 'updatedAt'] as const
  $columns = GuardianSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare guardianName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phone: string
  @column()
  declare relation: string
  @column()
  declare status: string
  @column()
  declare studentName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['createdAt', 'focusArea', 'id', 'managerName', 'memberCount', 'progress', 'status', 'teamName', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare focusArea: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare managerName: string
  @column()
  declare memberCount: number
  @column()
  declare progress: number
  @column()
  declare status: string
  @column()
  declare teamName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
